### PR TITLE
Fix #280 - `open_buffer` mangles the content of the buffer it is given.

### LINKED ISSUE #280: `open_buffer` mangles the content of the buffer it is given.
Here, you can use absolutely any ZIP file for `test.zip`:

```
require 'zip'
buf = nil
File.open('test.zip', "rb") { |f| buf = f.read }
File.open("before.zip", "wb") { |f| f << buf } 
Zip::File.open_buffer(buf) { |zf| nil # Do nothing at all!!! }
File.open("after.zip", "wb") { |f| f << buf }
```

Note that `after.zip` differs from `before.zip`, despite the fact that there's absolutely no reason to be changed.

However, if you do:

```
File.open('test.zip', "rb") { |f| buf = f.read }
Zip::File.open_buffer(buf.freeze) { |zf| zf.entries.first }
File.open("after.zip", "wb") { |f| f << buf }
```

then everything works perfectly, `buf` is not damaged and nothing crashes.

### PR DESCRIPTION
**Pull request by hainesr**
Things are now more carefully set up, and if a buffer is passed in which represents a file that already exists then this is taken into account. All initialization is now done in File.new, rather than being split between there and File.open_buffer.

This has also needed a bit of a re-write of Zip::File.initialize. I've tried to bring some logic to it as a result, and have added comments to explain what is now happening.

This PR includes some other related fixes too. All tests pass.

### CODE REVIEW

File: test/file_test.rb [hunk 1]
```diff
@@ -107,13 +114,14 @@ def test_open_buffer_with_stringio
   def test_close_buffer_with_stringio
     string_io = StringIO.new File.read('test/data/rubycode.zip')
     zf = ::Zip::File.open_buffer string_io
-    assert(zf.close || true) # Poor man's refute_raises
+    assert_nil zf.close
   end
 
   def test_close_buffer_with_io
     f = File.open('test/data/rubycode.zip')
```
Comment (jdleesmiller) [inline test/file_test.rb]: Note: this is similar (but not identical) to the test cases in https://github.com/rubyzip/rubyzip/issues/146 and https://github.com/rubyzip/rubyzip/issues/192, so they can probably be closed once we sort this out.

File: lib/zip/file.rb [hunk 2]
```diff
@@ -64,24 +64,38 @@ class File < CentralDirectory
 
     # Opens a zip archive. Pass true as the second parameter to create
     # a new archive if it doesn't exist already.
-    def initialize(file_name, create = false, buffer = false, options = {})
+    def initialize(path_or_io, create = false, buffer = false, options = {})
       super()
-      @name    = file_name
+      @name    = path_or_io.respond_to?(:path) ? path_or_io.path : path_or_io
```
Comment (jdleesmiller) [inline lib/zip/file.rb]: I think this is good... but it seems a bit optional. Was it aimed at solving a particular problem?

**Comment by hainesr** [comment]
Thanks for picking this up! It's been a while since I looked at this, but I'll try and find time to get it all back in my head and respond properly soon. As I remember it though, it turned into one of those problems that uncovered all sorts of other problems, and was originally a piece of code that was rather unclear as to what was going on 😬

**Comment by jdleesmiller** [comment]
I reviewed this again today, and I think it is good to merge. Thanks again for the fix.

**Comment by hainesr** [comment]
Sorry for not getting round to looking at it again myself; a change of role at work has left little time for extra-curricular coding recently, but I hope to get back into it again soon.

Thanks for merging, and thanks for picking up maintaining this gem @jdleesmiller.

**Comment by jdleesmiller** [comment]
Definitely get that :) I was able to progress this mainly because we had a hackathon day at my company, Overleaf. I will work it up into a new release.

**Comment by hainesr** [comment]
Oh cool. I'm a big fan of Overleaf!
