### PR TITLE
Fixes for the UniversalTime extra field

### LINKED ISSUE #395: Options not working in File class
This code
https://github.com/rubyzip/rubyzip/blob/249775f5637e6d65112574b3ac1763dc2393c7f6/lib/zip/file.rb#L88-L89
doesn't do what it is intended to do, because when you pass in `restore_permissions: false` or `restore_times: false`, it will be evaluating to `false || true`, which will always be `true`

### PR DESCRIPTION
**Pull request by hainesr**
When working on #413 to fix #395 I discovered that there were a few problems with how the timestamps were being stored - particularly with the UniversalTime extra field. On even closer inspection, and after having consulted the UniversalTime specification (ftp://ftp.info-zip.org/pub/infozip/doc/), I found further issues.

This PR fixes those issues and makes the `UniversalTime` class more user-friendly. It also adds tests.

At a later date I will fold this in so that it is used to store and restore the timestamps of files, but I've left this for now as it has the side-effect of adding data (that might be unexpected/unwanted) between the filename and file data. In short, I wonder if we should allow some control over which extra fields are used, rather than inserting them by default, c.f. #398.

### CODE REVIEW

**Comment by hainesr** [comment]
Sorry to bump this, but would you mind having a look @jdleesmiller?

File: lib/zip/extra_field/universal_time.rb [hunk 1]
```diff
@@ -8,20 +8,52 @@ def initialize(binstr = nil)
...
-      binstr && merge(binstr)
+      @flag  = 0
+
+      merge(binstr) unless binstr.nil?
+    end
+
+    attr_reader :atime, :ctime, :mtime, :flag
+
+    def atime=(time)
+      time.nil? ? @flag &= 0b101 : @flag |= 0b010
```
Comment (jdleesmiller) [inline lib/zip/extra_field/universal_time.rb]: Maybe it's worth extracting these masks into constants? Something like
```rb
ATIME_MASK = 0b010
@flag = time.nil? ? @flag & ~ATIME_MASK : @flag | ATIME_MASK
```

File: lib/zip/extra_field/universal_time.rb [hunk 2]
```diff
@@ -8,20 +8,52 @@ def initialize(binstr = nil)
...
-      mtime && @mtime ||= ::Zip::DOSTime.at(mtime)
-      atime && @atime ||= ::Zip::DOSTime.at(atime)
-      ctime && @ctime ||= ::Zip::DOSTime.at(ctime)
+      return if size.nil? || size <= 0
+
+      flags, *times = content.unpack('Cl<l<l<')
+      @flag = flags
+
+      # Parse the timestamps, in order, based on which flag is set.
+      times.each do |time|
```
Comment (jdleesmiller) [inline lib/zip/extra_field/universal_time.rb]: I think your reading of the spec is correct --- good find. I think it may be (marginally) clearer without the loop, if this also looks right to you?
```rb
@flag, *times = content.unpack('Cl<3')
return if times[0].nil?
@mtime ||= ::Zip::DOSTime.at(times.shift) unless @flag & MTIME_MASK == 0
return if times[0].nil?
@atime ||= ::Zip::DOSTime.at(times.shift) unless @flag & ATIME_MASK == 0
return if times[0].nil?
@ctime ||= ::Zip::DOSTime.at(times.shift) unless @flag & CTIME_MASK == 0
```

File: lib/zip/extra_field/universal_time.rb (hunk 1 above)
Comment (hainesr) [reply lib/zip/extra_field/universal_time.rb]: Agreed. I'll do that.

File: lib/zip/extra_field/universal_time.rb [hunk 3]
```diff
@@ -8,20 +8,52 @@ def initialize(binstr = nil)
...
     def merge(binstr)
       return if binstr.empty?
+
       size, content = initial_parse(binstr)
-      size || return
-      @flag, mtime, atime, ctime = content.unpack('CVVV')
-      mtime && @mtime ||= ::Zip::DOSTime.at(mtime)
-      atime && @atime ||= ::Zip::DOSTime.at(atime)
-      ctime && @ctime ||= ::Zip::DOSTime.at(ctime)
+      return if size.nil? || size <= 0
```
[the remark this answers is not in the document]
Comment (hainesr) [reply lib/zip/extra_field/universal_time.rb]: Hmm, yes. That should be `!size` not `size.nil?`. Will fix.

File: lib/zip/extra_field/universal_time.rb (hunk 2 above)
Comment (hainesr) [reply lib/zip/extra_field/universal_time.rb]: This is somewhat neater and doesn't need a second copy of the flags. I'll go with this.

**Comment by hainesr** [comment]
Thanks for the review. I have made the above fixes and have rebased onto current `master`.
